export const CUSTOMER_REQUEST = "CUSTOMER_REQUEST";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const CUSTOMER_ERROR = "CUSTOMER_ERROR";

export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_SINGLE_CUSTOMER_DETAILS_BY_ID = "GET_SINGLE_CUSTOMER_DETAILS_BY_ID";
export const GET_SINGLE_CUSTOMER_DETAILS_BY_PASSPORT = "GET_SINGLE_CUSTOMER_DETAILS_BY_PASSPORT";

